version: '3'
services:
  api:
    build: .
    restart: always
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file: .env

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
    
    ports:
      - 5432:5432
    
    volumes:
      - postgres-db:/var/lib/postgresql/data
    
volumes:
    postgres-db:

# # version: ""

# # services:
# #   api_db:
# #     image: postgres
# #     # restart: always
# #     environment:
# #       POSTGRES_DB: app
# #       POSTGRES_USER: postgres
# #       POSTGRES_PASSWORD: password123
    
# #     container_name: api_db
# #     ports:
# #       - "5432:5432"

# #   api:
# #     build:
# #       context: .
# #       dockerfile: Dockerfile
# #     container_name: api
# #     # restart: always
# #     depends_on:
# #       - api_db
# #     ports:
# #       - "8000:8000"
# #     env_file:
# #       - ./.env
# #     volumes:
# #       - .:/app